import { StyleSheet } from 'react-native';
import { colors } from '@/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.lightSecondary,
  },
  header: {
    backgroundColor: colors.secondary[500],
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: colors.common.white,
    flex: 1,
    textAlign: 'center',
  },
  headerSpacer: {
    width: 40,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 24,
  },
  sectionCard: {
    backgroundColor: colors.background.light,
    borderRadius: 18,
    marginBottom: 16,
    shadowColor: colors.common.black,
    shadowOpacity: 0.03,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
    overflow: 'hidden',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  sectionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionHeaderText: {
    flex: 1,
    gap: 4,
  },
  sectionTitle: {
    color: colors.text.primary,
    fontFamily: 'Outfit-SemiBold',
  },
  sectionSubtitle: {
    color: colors.text.secondary,
  },
  sectionContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  profilePictureSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  profilePictureContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.secondary[500],
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  changePhotoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: colors.secondary[50],
    marginBottom: 8,
  },
  changePhotoText: {
    color: colors.secondary[500],
    fontFamily: 'Outfit-Medium',
  },
  photoHint: {
    color: colors.text.secondary,
  },
  inputField: {
    marginBottom: 16,
  },
  emailVerificationNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: -8,
    marginBottom: 16,
    paddingLeft: 4,
  },
  emailVerificationText: {
    color: colors.accent.blue,
  },
  dropdownContainer: {
    marginBottom: 16,
  },
  dropdownField: {
    backgroundColor: colors.background.light,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border.medium,
    paddingHorizontal: 16,
    paddingVertical: 14,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dropdownLabel: {
    color: colors.text.secondary,
    fontFamily: 'Outfit-Medium',
    marginBottom: 8,
  },
  dropdownValue: {
    color: colors.text.primary,
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    flex: 1,
  },
  toggleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  toggleContent: {
    flex: 1,
    marginRight: 16,
    gap: 4,
  },
  toggleLabel: {
    color: colors.text.primary,
    fontFamily: 'Outfit-Medium',
  },
  toggleDescription: {
    color: colors.text.secondary,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: colors.background.light,
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border.medium,
  },
  cancelButtonText: {
    color: colors.text.primary,
    fontFamily: 'Outfit-SemiBold',
  },
  saveButton: {
    flex: 1,
    backgroundColor: colors.secondary[500],
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  saveButtonText: {
    color: colors.common.white,
    fontFamily: 'Outfit-SemiBold',
  },
  roleButton: {
    backgroundColor: colors.secondary[50],
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  roleButtonText: {
    color: colors.secondary[500],
    fontFamily: 'Outfit-SemiBold',
  },
  infoNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: colors.accent.blue + '10',
    borderRadius: 12,
  },
  infoNoteText: {
    flex: 1,
    color: colors.accent.blue,
  },
  warningBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: colors.status.warningLight,
    borderRadius: 12,
    marginBottom: 16,
  },
  warningText: {
    flex: 1,
    color: colors.status.warning,
    fontFamily: 'Outfit-Medium',
  },
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.background.lightSecondary,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border.medium,
    marginBottom: 8,
  },
  uploadButtonText: {
    color: colors.text.primary,
    fontFamily: 'Outfit-Medium',
  },
  uploadHint: {
    color: colors.text.secondary,
    paddingLeft: 4,
  },
  servicePhotosSection: {
    marginTop: 8,
  },
  servicePhotosLabel: {
    color: colors.text.primary,
    fontFamily: 'Outfit-Medium',
    marginBottom: 12,
  },
  actionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
    backgroundColor: colors.background.lightSecondary,
    borderRadius: 12,
    marginBottom: 8,
  },
  actionItemText: {
    color: colors.text.primary,
    fontFamily: 'Outfit-Medium',
  },
  dangerTitle: {
    color: colors.status.error,
  },
  dangerText: {
    color: colors.text.secondary,
    marginBottom: 16,
    lineHeight: 20,
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.common.white,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.status.error,
  },
  deleteButtonText: {
    color: colors.status.error,
    fontFamily: 'Outfit-SemiBold',
  },
});

