import { StyleSheet } from 'react-native';
import { colors } from '@/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.lightSecondary,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  header: {
    backgroundColor: colors.secondary[500],
    paddingHorizontal: 16,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: colors.common.white,
  },
  profileSection: {
    alignItems: 'center',
    marginTop: -60,
    marginBottom: 20,
    padding: 16,
    backgroundColor: colors.common.white,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 18,
  },
  avatarCircleLarge: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.secondary[500],
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 4,
    borderColor: colors.common.white,
  },
  nameTextCentered: {
    color: colors.text.primary,
    fontFamily: 'Outfit-SemiBold',
    marginBottom: 8,
  },
  serviceProviderTag: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: colors.accent.orange,
    marginBottom: 8,
  },
  serviceProviderText: {
    color: colors.common.white,
    fontFamily: 'Outfit-Medium',
  },
  locationRowCentered: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 16,
  },
  profileCard: {
    position: 'absolute',
    width: '100%',
    backgroundColor: colors.background.light,
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 16,
    shadowColor: colors.common.black,
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    bottom: -50,
    zIndex: 1000,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },

  avatarCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.secondary[200],
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileTextBlock: {
    flex: 1,
    gap: 4,
  },
  nameText: {
    color: colors.text.primary,
    fontFamily: 'Outfit-SemiBold',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  locationText: {
    color: colors.text.secondary,
  },
  contactButtonsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
    width: '100%',
  },
  whatsappButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 16,
    paddingVertical: 10,
    backgroundColor: colors.secondary[500],
  },
  emailButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 16,
    paddingVertical: 10,
    backgroundColor: colors.accent.blue,
  },
  contactButtonText: {
    color: colors.common.white,
    fontFamily: 'Outfit-Medium',
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    borderRadius: 16,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: colors.background.light,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  editButtonCentered: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: colors.common.white,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  editButtonText: {
    color: colors.text.primary,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    marginTop: 70,
  },
  itemsRow: {
    marginTop: 20,
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
  },
  primaryActionButton: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.secondary[500],
    flexDirection: 'row',
    gap: 8,
  },
  primaryActionText: {
    color: colors.common.white,
    fontFamily: 'Outfit-Medium',
  },
  secondaryActionCard: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border.light,
    backgroundColor: colors.background.light,
    gap: 6,
  },
  secondaryActionLabel: {
    color: colors.text.primary,
  },
  networkCard: {
    marginTop: 20,
    marginHorizontal: 16,
    borderRadius: 18,
    backgroundColor: colors.primary[700],
    padding: 18,
    gap: 8,
  },
  networkTitle: {
    color: colors.common.white,
    fontFamily: 'Outfit-SemiBold',
  },
  networkSubtitle: {
    color: colors.common.white,
  },
  joinNetworkButton: {
    marginTop: 8,
    backgroundColor: colors.common.white,
    borderRadius: 16,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  joinNetworkButtonText: {
    color: colors.primary[700],
    fontFamily: 'Outfit-SemiBold',
  },
  sectionWrapper: {
    paddingHorizontal: 16,
    paddingTop: 20,
    gap: 10,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sectionTitle: {
    color: colors.text.primary,
    fontFamily: 'Outfit-SemiBold',
  },
  sectionBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: colors.background.lightSecondary,
  },
  sectionBadgeText: {
    color: colors.neutral[900],
    backgroundColor: colors.background.neutral,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 10,
    marginLeft: 'auto',
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  quickActionButton: {
    width: '47%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: colors.background.light,
    gap: 8,
  },
  quickActionIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionLabel: {
    color: colors.text.primary,
    fontFamily: 'Outfit-Medium',
  },
  dashboardCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background.light,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    gap: 12,
    shadowColor: colors.common.black,
    shadowOpacity: 0.03,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  dashboardCardIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardCardContent: {
    flex: 1,
    gap: 4,
  },
  dashboardCardTitle: {
    color: colors.text.primary,
    fontFamily: 'Outfit-SemiBold',
  },
  dashboardCardSubtitle: {
    color: colors.text.secondary,
    fontFamily: 'Outfit-Medium',
  },
  dashboardCardRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pendingTag: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: colors.status.warningLight,
  },
  pendingTagText: {
    color: colors.status.warning,
    fontFamily: 'Outfit-Medium',
  },
  listingsContainer: {
    marginTop: 8,
    marginBottom: 8,
    paddingLeft: 8,
  },
  safetyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background.light,
    borderRadius: 16,
    padding: 16,
    marginBottom: 8,
    gap: 12,
  },
  safetyItemText: {
    flex: 1,
    color: colors.text.primary,
    fontFamily: 'Outfit-Medium',
  },
  listingCard: {
    flexDirection: 'row',
    borderRadius: 16,
    backgroundColor: colors.background.light,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
    width: '100%',
    shadowColor: colors.common.black,
    shadowOpacity: 0.03,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  listingImagePlaceholder: {
    width: 64,
    height: 64,
    borderRadius: 12,
    backgroundColor: colors.background.lightSecondary,
  },
  listingInfo: {
    flex: 1,
    gap: 4,
  },
  listingHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  listingTitle: {
    color: colors.text.primary,
    fontFamily: 'Outfit-SemiBold',
  },
  listingSubtitle: {
    color: colors.text.secondary,
    fontFamily: 'Outfit-Medium',
  },
  listingStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  statusPillApproved: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: colors.status.successLight,
  },
  statusPillPending: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: colors.status.warningLight,
  },
  statusPillTextApproved: {
    color: colors.status.success,
  },
  statusPillTextPending: {
    color: colors.status.warning,
  },
  listingMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  logoutButtonWrapper: {
    paddingHorizontal: 16,
    paddingTop: 24,
  },
  guidelinesButton: {
    borderRadius: 20,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.light,
    borderWidth: 1,
    borderColor: colors.primary[200],
    flexDirection: 'row',
    gap: 8,
  },
  guidelinesText: {
    color: colors.primary[800],
  },
  logoutButton: {
    borderRadius: 20,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.light,
    borderWidth: 1,
    borderColor: colors.status.error,
    flexDirection: 'row',
    gap: 8,
  },
  logoutText: {
    color: colors.status.error,
    fontFamily: 'Outfit-SemiBold',
  },
  listingActionText: {
    color: colors.text.primary,
  },
  listingSeparator: {
    height: 10,
  },
  listingPrice: {
    color: colors.text.primary,
    fontFamily: 'Outfit-SemiBold',
    marginRight: 8,
  },
  billsIncludedTag: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: colors.status.successLight,
  },
  billsIncludedText: {
    color: colors.status.success,
    fontFamily: 'Outfit-Medium',
  },
  savedDateText: {
    color: colors.text.secondary,
    fontFamily: 'Outfit-Normal',
    fontSize: 12,
    marginLeft: 4,
  },
});


