import { StyleSheet } from 'react-native';
import { colors } from '@/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.lightSecondary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 32,
  },
  iconContainer: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 24,
  },
  iconWrapper: {
    width: 70,
    height: 70,
    borderRadius: 16,
    backgroundColor: colors.secondary[500],
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.common.black,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  titleContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  title: {
    fontFamily: 'Outfit-Bold',
    fontSize: 28,
    color: colors.text.primary,
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    color: colors.text.secondary,
    opacity: 0.7,
    textAlign: 'center',
  },
  ageRequirementsBox: {
    backgroundColor: '#EEF5FF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 32,
    borderWidth: 1,
    borderColor: '#C7D8FF',
  },
  ageRequirementsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  infoIconContainer: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: colors.primary[500],
    backgroundColor: colors.common.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ageRequirementsTitle: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 16,
    color: colors.primary[500],
  },
  bulletPoints: {
    gap: 8,
    marginBottom: 12,
  },
  bulletPoint: {
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    color: colors.primary[500],
    lineHeight: 20,
  },
  bulletPointBold: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 14,
    color: colors.primary[500],
  },
  complianceText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 12,
    color: colors.primary[500],
    opacity: 0.9,
    lineHeight: 16,
  },
  dateInputSection: {
    marginBottom: 24,
  },
  dateLabel: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 16,
    color: colors.text.primary,
    marginBottom: 12,
  },
  dateInputsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  dateInputWrapper: {
    flex: 1,
  },
  dateInput: {
    height: 56,
    borderWidth: 1,
    borderColor: colors.border.light,
    borderRadius: 12,
    paddingHorizontal: 0,
    fontFamily: 'Outfit-Regular',
    fontSize: 16,
    color: colors.text.primary,
    backgroundColor: colors.common.white,
    textAlign: 'center',
    marginBottom: 8,
  },
  dateInputLabel: {
    fontFamily: 'Outfit-Regular',
    fontSize: 12,
    color: colors.text.secondary,
    opacity: 0.7,
    textAlign: 'center',
  },
  errorText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    color: colors.status.error,
    marginTop: 4,
  },
  errorBox: {
    backgroundColor: '#FFE5E5',
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#FFB3B3',
  },
  errorBoxText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    color: '#CC0000',
    lineHeight: 20,
    marginBottom: 4,
  },
  consentBox: {
    backgroundColor: '#F3E8FF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#E9D5FF',
  },
  consentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  consentIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.accent.purple,
    alignItems: 'center',
    justifyContent: 'center',
  },
  consentTitle: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 18,
    color: colors.accent.purple,
  },
  consentDescription: {
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    color: colors.accent.purple,
    lineHeight: 20,
    marginBottom: 16,
  },
  checkboxContainer: {
    marginBottom: 16,
  },
  parentEmailSection: {
    marginTop: 8,
  },
  parentEmailLabel: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 16,
    color: colors.text.primary,
    marginBottom: 8,
  },
  parentEmailInput: {
    height: 48,
    borderWidth: 1,
    borderColor: colors.border.light,
    borderRadius: 12,
    paddingHorizontal: 16,
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    color: colors.text.primary,
    backgroundColor: colors.common.white,
    marginBottom: 8,
  },
  parentEmailInputError: {
    borderColor: colors.status.error,
  },
  helperText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 12,
    color: colors.text.secondary,
    opacity: 0.7,
    lineHeight: 16,
  },
  consentErrorBox: {
    backgroundColor: colors.status.errorLight,
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: colors.status.error,
  },
  consentErrorText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    color: colors.status.error,
    lineHeight: 20,
  },
  verifyButton: {
    marginBottom: 24,
    borderRadius: 16,
  },
  privacyNoticeBox: {
    backgroundColor: colors.background.lightTertiary,
    borderRadius: 12,
    padding: 16,
  },
  privacyNoticeTitle: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 16,
    color: colors.text.primary,
    marginBottom: 8,
  },
  privacyNoticeText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    color: colors.text.primary,
    lineHeight: 20,
  },
});

